image: node:14-alpine
pages: 
  cache: 
    paths:
      - .next/
      - .npm/ 
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run export
    - rm -rf public
    - mkdir -p public
    - cp -r out/* public
  interruptible: true
  artifacts:
    paths:
      - public
  only:
    - master