image: node:14.7.0
pages: 
  script:
    - npm install
    - npm run export
    - rm -rf public
    - mkdir -p public
    - cp -r out/* public
  artifacts:
    paths:
      - public
  only:
    - master