name: Swing TX Left
logo: /files/swing_tx_left_720final-e1564565077506.png
home: home
navigationBar:
  - page: home
    text: Home
  - page: about
    text: About
  - page: voting-and-election-resources
    text: Voting and Election Resources
  - page: home
    text: Events
    id: events
footer:
  - target: _self
    text: team@swingtx7left.org
    url: mailto:team@swingtx7left.org
  - target: _blank
    text: Facebook
    url: https://www.facebook.com/swingtexasleft/
  - target: _blank
    url: https://www.instagram.com/swingtexasleft/
    text: Instagram
  - target: _blank
    text: Twitter
    url: https://twitter.com/swingtxleft
mobilizeOrgs:
  - regexp:
      - flags: i
        pattern: swing\s*tx\s*left
      - flags: i
        pattern: STXL
    url: https://api.mobilize.us/v1/organizations/210/events?timeslot_end=gte_now
  - url: https://api.mobilize.us/v1/organizations/2441/events?timeslot_end=gte_now
