backend:
  name: git-gateway
media_folder: public/files
public_folder: /files
collections: 
  - label: pages
    name: pages
    format: yml
    extension: yml
    folder: pagecontent
    editor:
      preview: false
    create: true
    fields:
      - name: title
        widget: string
      - name: slug
        widget: slugunique
      - name: mainImage
        widget: image 
        required: false
      - name: mainImageFullPage
        widget: boolean
        default: false
      - name: content
        widget: list
        collapsed: false
        default: []
        types:
          - name: normal-section
            widget: object
            fields:
              - name: header
                widget: string
              - name: showHeader
                widget: boolean
                default: true
              - name: id
                widget: string
                pattern: ['^[\w]+$','a-z A-Z 0-9 _' ]
                required: false
              - name: content
                widget: html
          - name: events
            fields:
              - name: header
                widget: string
              - name: showHeader
                widget: boolean
                default: true
              - name: id
                widget: string
                pattern: ['^[\w]+$','a-z A-Z 0-9 _' ]
                required: false
          - name: sections-with-toc
            fields:
              - name: header
                widget: string
              - name: showHeader
                widget: boolean
                default: true
              - name: id
                widget: string
                pattern: ['^[\w]+$','a-z A-Z 0-9 _' ]
                required: false
              - name: content
                widget: html
              - name: sections
                widget: list
                collapsed: false
                types:
                    - name: normal-section
                      widget: object
                      fields:
                        - name: header
                          widget: string
                        - name: showHeader
                          widget: boolean
                          default: true
                        - name: id
                          widget: string
                          pattern: ['^[\w]+$','a-z A-Z 0-9 _' ]
                          required: true
                        - name: content
                          widget: html
      - name: mainButtons
        widget: list
        default: []
        fields:
          - name: alignment
            widget: select
            options:
              - left
              - center
              - right
          - name: buttons
            widget: list
            types:
              - name: popup
                widget: object
                fields: 
                  - name: text
                    widget: string
                  - name: content
                    widget: html
              - name: link
                widget: object
                fields: 
                  - name: text
                    widget: string
                  - name: link
                    widget: string
                  - name: newTab
                    widget: boolean
                    default: false
      - name: pageMainMessage
        widget: html
        required: false
      - name: pageMainMessageShow
        widget: boolean
        default: false
        required: false
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      - name: siteSettings
        label: Web Site Settings
        file: settings.yml
        format: yml
        extension: yml
        editor:
          preview: false
        fields:
        - name: name
          widget: string
        - name: logo
          widget: image
        - name: home
          widget: relation
          collection: pages
          valueField: slug
          searchFields: 
            - title
            - slug
          displayFields:
            - "URL: /{{slug}} Title: {{title}}"
        - name: navigationBar
          widget: list
          collapsed: false
          fields:
            - name: page
              widget: relation
              collection: pages
              valueField: slug
              searchFields: 
                - title
                - slug
              displayFields:
                - "URL: /{{slug}} Title: {{title}}"
            - name: text
              widget: string
            - name: id
              widget: string
              required: false
        - name: footer
          widget: list
          collapsed: false
          fields:
            - name: text
              widget: string
            - name: url
              widget: string
            - name: target
              label: open in new tab etc
              widget: select
              default: _self
              options: [_self,_blank]
            
local_backend: true
